language: node_js
node_js:
- lts/*
script:
- echo "Smoke testing d2 executable"
- "./packages/main/bin/d2 debug system"
- yarn test
deploy:
- provider: script
  skip_cleanup: true
  script:
  - "./packages/utils/bin/d2-utils release --publish npm"
  on:
    tags: false
    branch: master
env:
  global:
  - GIT_AUTHOR_NAME=@dhis2-bot
  - GIT_AUTHOR_EMAIL=apps@dhis2.org
  - GIT_COMMITTER_NAME=@dhis2-bot
  - GIT_COMMITTER_EMAIL=apps@dhis2.org
  - secure: hVQX6pQ4oGzbYRWWeL2cbZTdzNRKrCqWrY3rtuRUkabisTs+6ZvMur35OiUQh/Jnypf8tk+/0mbo1iMSbsIgtHYeq6bQPssXrdWLH12yY7dG0KYrUhO+rXm5xCmnuZt3MaU194YsEb4yl6uVetXtlFqRR1r0aaIJTKPdRTGZvarP+WpAONfb3/Kvnx3cs8agWx2tV6BEnXOdGcC1YX35sZF8OXV9E6wt6NQ4cykfDFyA02LKMREpFW3ydGHa62lGa0i3z2wX89ZVGs/KN0K5e3OIlsf7vyXRnw38eEaL7qDkjMiAWfa/FBx8nnO5pbuY9EoIbL0zhEAUohAOaNOAr+ezD3P8EtXZFxHLFqrQoAUM9JXh/2hGFVkDOzitUr2dMVI0Xt/KxsoBnvkSOStxvXUvJRitr6A6W1R8246SwEyrKaWCmSkbrf/Vw88ltB6ZnuAQ+in/+6A2GMf2PN3xJmMphdMPuywgBxbGj3WfBC1ySMoymQcSt187aeViEXKTsGY4CA2mJtKrOPcWppydKEu0QOV+A0keQlQL7w/VDRfZ0vSRB7dEiySPjtuRxnQJWDuPhwFVuwEyGsdBGrwp4dIQmztapSGYxJuD6H/hjMW7TKslxI4VnRR6YSbgF5GV0cHSIJp2kveAf7GXCwQdhKqiUUD62tNap7fD5cGfjls=
  - secure: cTG1m01eSs51lPt0JKeDN174peKBsuxxbiN8SuBL+LPbS9onlQuP3tZNCTzAbpOX3ydsbcUnnkqMoQYFnikbHl4Hi/CAUTzAYRra+MWDzdybmvSyBw7eaSpNrAPR6xoIYL0kUgia25fhvuX5dMrYnZ+hPMLlGeN0b1cm1bihNZr0f3HQouuOqY2Z4CV0d3wzkZWq02FPNMlngR0mOiNLEiRFePu427OJtH5cHws/JgE9RCQy/9bDuxRluY3SdGCmMWpQAucLwhDZ7QMctB9kNyUH72gLo9arR836nS6HeImpb7DwxJO8VmgEXIBggfUwd6tL6nZBZvyqWTeS8KqcX8bnil3+kxhhi4Z1So5XskT+ZnTwwsW1L2sjF1NCfj6b9vNbU9RDe/bn7Kv7NSA3MXt4y6GlpfZ6FSG8Dn/F1HNRlEdvPfhy2zNZqyVr5Qi8P1KkKZXWxPCMHd1bdNAnOW0G/o0/ELa3oB0kfi6d/HooDPD/4r0JMIMDzWKtjm6BkjJmzKvMXxNaZozfMeQi0ui4hr4kbGRVsDIgwSf1yLCnBCEQguQa1ZdnPum2MpKnMaJYUF8H2RS/5PF16tlTAf2jS2gzo6DMMREH0AiVMT5rNcURGdqnQIFRU4VzUdM000nAD53/7iNIDugJ/0lsF9VCQtEt+8ghutz+wltuvlc=
