language: node_js
node_js:
- lts/*
script:
- echo "Smoke testing d2 executable"
- "./packages/main/bin/d2 debug system"
- yarn test
deploy:
- provider: script
  skip_cleanup: true
  script:
  - "./packages/utils/bin/d2-utils release --publish npm"
  on:
    tags: false
    branch: master
env:
  global:
  - GIT_AUTHOR_NAME=@dhis2-bot
  - GIT_AUTHOR_EMAIL=apps@dhis2.org
  - GIT_COMMITTER_NAME=@dhis2-bot
  - GIT_COMMITTER_EMAIL=apps@dhis2.org
  - secure: WMu2f5d2AkwYMZEisCtMfc5rSrV8TcMmom2qvaDLk2+2AHcupWUXZWPv8NUJnYYdtqmfoS7pTFz0TmIQ7i+XVK4HDnxE+ksq/byXn0UNj9p8OB6c8RsJJqSL7c8HT1k6yQxseKnPHRE6jTiVXIgq3SkY32bYGgB7ZmxNTcjmmmPhmvXYJzfgIsM2b5hA/FW1sDtnLXFS9F6GLgF9p99eNP810zBrtxcGcXFuRhNpLv9IGJd4QSh4NsKak+4z/w8L+oaWbF0FUAJY5MjelL99lIPG5M6RIdoxAWLDbw2a568lsrGr7CuMzZz/Z0gXWWta5KRoB66YRpDdtZtY3Qh4PWlMKPONy7RcTr3XX7tDykh1EXHwiYyfSNlqBO/TWsK5bC9gbjM+q+jNR6SDudVIqSHGjrev/x9P0eFF/W7hGd6/0zMkz7BJWYfSkiLLNzkk6wtiHBvk3gh9bCgmIhn2c6N8HDFKTd70PJ2lFZBfhu1O2NEVH7W4KFFXNj8JgIUps9KmIjpfSilYBJNHGH0UAZdzQEijG8shtM2y/RBvysnByLJxrSnqSAeJPx7CfTam3Q0QWIwa5TIuIzWJSTwtYv5PY+Y6EzL0LhLaFB4vg+66e+zha6E1oZPfOKFWdJkt7Kl++IQegIsVFRKqei61rkP9Fx7gu82hRKXz1ljLb9o=
  - secure: EnTJ5emmdlkHgpv3akmLaWMuILqKlXKi3XxtCsYDuMmb4gfPTP6ubpFzrHi82cF23NDhljgedpvEZ8omdxZolk8mYqX0dPq6FTLr49OIf7GdE9vPeqPbq1YKDesXuI6iuvCBCkDmgWErMdmF0NTmwd24W6M3CmsJ7q38v31c7gNyjWu7sX4qiLO1o5WnxLXZ7DBfljJd79trdAaCebHb2Vfz7u16kpMT+w77BlVueFiCTqLQe8BZ0SnMOB/hKmBbPMx/qZ6czp/EXCWdFj/xzN7yJoF23xiTSMHtnfSjQmQTJVQPCfJKi5VvCQe2r2jyeg2Q6JbyBW27Y7BUMaAs9cE38Sr34xzzQghLSbiQehUxTHn+RbV9t1FKMOezx4jmgxLtLvJ9+gmZOzosgoOt9iZc4Jw1kon3mRhi9G7YD066+hUaObKNDYGfIomWrnZWPDARELunNBLiHhS+eBg+gJT19xuaELciFToG+/GWUP00ww+PhzrvmI5YeYY+tCpnkY08fMIRbn2c51XTpCxDScH7xVDAYL0M3+PkcfUboAmRTBWc7KlUzAJcarPgb/w/78vkLeOQNC64VySJH3X9AjBTwybgf2T8oIezIOuNIToxam4rNqtZmLo8K+IvufHMh6wZyEbj3ZZKewvLlK6e8kxo6IPmQB+NFUe8MLtk1Zo=
