name: 'dhis2-node lint'

on: push

jobs:
    check:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Run linters
              run: |
                  npx d2-style js check
                  npx d2-style text check
        env:
            CI: true
